[32m2022-06-23 23:38:28 +0300[0m - dagster - [34mDEBUG[0m - growjo_job - f97700a3-5529-442a-a43e-0e91d003bb03 - 45710 - parse_load_growjo - LOGS_CAPTURED - Started capturing logs for step: parse_load_growjo.
[32m2022-06-23 23:38:28 +0300[0m - dagster - [34mDEBUG[0m - growjo_job - f97700a3-5529-442a-a43e-0e91d003bb03 - 45710 - parse_load_growjo - STEP_START - Started execution of step "parse_load_growjo".
[32m2022-06-24 00:03:40 +0300[0m - dagster - [34mERROR[0m - [31mgrowjo_job - f97700a3-5529-442a-a43e-0e91d003bb03 - 45710 - parse_load_growjo - STEP_FAILURE - Execution of step "parse_load_growjo" failed.

dagster.core.errors.DagsterExecutionInterruptedError

Stack Trace:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dagster/core/execution/plan/execute_plan.py", line 226, in dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dagster/core/execution/plan/execute_step.py", line 353, in core_dagster_event_sequence_for_step
    for user_event in check.generator(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dagster/core/execution/plan/execute_step.py", line 69, in _step_output_error_checked_user_event_sequence
    for user_event in user_event_sequence:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dagster/core/execution/plan/compute.py", line 174, in execute_core_compute
    for step_output in _yield_compute_results(step_context, inputs, compute_fn):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dagster/core/execution/plan/compute.py", line 142, in _yield_compute_results
    for event in iterate_with_context(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dagster/utils/__init__.py", line 406, in iterate_with_context
    next_output = next(iterator)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dagster/core/execution/plan/compute_generator.py", line 66, in _coerce_solid_compute_fn_to_iterator
    result = fn(context, **kwargs) if context_arg_provided else fn(**kwargs)
  File "/Users/key/Documents/GitHub/hn_launches_analytics/pipeline/ops/parse_load_growjo.py", line 31, in parse_load_growjo
    time.sleep(np.random.poisson(5))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dagster/utils/interrupts.py", line 74, in _new_signal_handler
    raise error_cls()
[0m
